spring:
  profiles.active: REST #REST STUBS
  thymeleaf:
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: true
  datasource:
    jndi-url: jdbc/frontendDbLink

apiService:
  baseUrl: "http://localhost:8081"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.thymeleaf: DEBUG
    org.springframework.web.client: DEBUG
