spring:
  profiles.active: JDBC_TEMPLATE
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./backend_db
    username: sa
    password:

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG